apiVersion: apps/v1
kind: Deployment
metadata:
  name: starter-service-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: starter-service-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3  # how many pods can be added in one time
      maxUnavailable: 0  # how many pods can be unavailable during rolling update, if set as 0 = no downtime, also can be set as %
  template:
    metadata:
      labels:
        app: starter-service-app
    spec:
      containers:
        - name: starter-service-app
          image: yky32/starter-service:latest  # plz choose the ecr path
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          resources:
            requests:
              cpu: 0.5
              memory: 1Gi
            limits:
              cpu: 1
              memory: 2Gi
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9000
            initialDelaySeconds: 60
            failureThreshold: 10
            timeoutSeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9000
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 5
#          env:
#            - name: DB_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: app-secret
#                  key: db_password
#            - name: DB_USERNAME
#              valueFrom:
#                configMapKeyRef:
#                  name: app-cm
#                  key: db_username
#            - name: DB_URL
#              valueFrom:
#                configMapKeyRef:
#                  name: app-cm
#                  key: db_url